export const COLOR_GOLD = "#b7903c"
export const COLOR_WHITE = "#ffffff"
export const COLOR_FOOTER_WHITE = "##b2b2b2"
export const COLOR_BLACK = "#000000"
export const COLOR_BLUE = "#56ccf2"
export const COLOR_RED = "#ff0000"